---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes

  - name: install apache2 package and apt-get update for Ubuntu only
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: install mysql and postgres

    apt:
      name:
        - nginx
      state: latest
    when: ansible_distribution in ['Debian']
