---

- hosts: all
  become: true
  tasks:

  - name: install updates (Debian)
    tags: always
    apt:
      update_cache: yes 
    when: ansible_distribution in ["Debian"]

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

- hosts: ubuntu_1
  become: true
  tasks:

  - name: remove mysql-server on Ubuntu_1
    tags: mysql-ubuntu-1 
    apt:
      name:
        - mysql-server
      state: absent

- hosts: ubuntu_2
  become: true
  tasks:

  - name: remove apache to Ubuntu-2 server
    tags: apache-for-ubuntu_2
    apt:
      name:
        - apache2
      state: absent

- hosts: ubuntu_3
  become: true
  tasks:

  - name: remove git to ubuntu_3
    tags: git_for_ubuntu3
    apt:
      name:
        - git-all
      state: absent

- hosts: debian_server
  become: true
  tasks:

  - name: remove nginx to debian server
    tags: nginx-for-debian
    apt:
      name:
        - nginx
      state: absent

